/**
 * data.js
 * Fuente única de verdad para la información de las personas integrantes del equipo.
 * Todas las páginas (portada, perfiles) leen de este array. No hay datos
 * personales "hardcodeados" en el HTML: todo se renderiza desde acá vía JS.
 *
 * NOTA: la información es ficticia, generada para cumplir con la consigna del TP1.
 */

const TEAM = [
  {
    id: 1,
    name: "Omar Dario Virili",
    role: "Técnico superior en electrónica",
    city: "Villa Ocampo, Santa Fe",
    age: 42,
    github: "https://github.com/odv144",
    initials: "VR",
    fotoPerfil: "https://avatars.githubusercontent.com/u/12345678?v=4",
    accent: "#2B2F77",
    bio: "Apacionado por la electrónica y el desarrollo web, fasinado por la robótica y la Inteligencia Artificial.",
    skills: [
      { name: "HTML5 & CSS3", level: 92 },
      { name: "Java", level: 50 },
      { name: "React", level: 70 },
      { name: "Node.js", level: 65 },
      { name: "Python", level: 60 },
    ],
    movies: ["Matrix", "Ex Machina", "Una Mente Brillante"],
    albums: ["La Esquina del Infinito — La Renga", "Signos — Soda Stereo", "Say no more — Charly Gracía"],
    funFacts: [
      "De técnico en electrónica a programador: cambié los cables sueltos por bugs sueltos.",
      "Técnico en electrónica de día, programador de noche, fan del rock nacional las 24 horas.",
      "Soldé placas antes de soldar código, y a los dos les seguí sacando chispas",
    ],
  },
  {
    id: 2,
    name: "Bruno Aguirre",
    role: "Backend Developer",
    city: "Córdoba, Córdoba",
    age: 25,
    github: "https://github.com/bruno-aguirre-dev",
    initials: "BA",
    fotoPerfil: "https://avatars.githubusercontent.com/u/12345678?v=4",
    accent: "#1C6E5E",
    bio: "Diseña APIs pensando en quien las va a odiar a las 3am de un incidente: la persona del futuro que es él mismo.",
    skills: [
      { name: "Node.js", level: 88 },
      { name: "Bases de datos SQL", level: 82 },
      { name: "APIs REST", level: 85 },
      { name: "Docker", level: 60 },
    ],
    movies: ["Interestelar", "Sr. Robot (serie)", "WarGames"],
    albums: ["The Dark Side of the Moon — Pink Floyd", "In Rainbows — Radiohead", "Bahía — Louta"],
    funFacts: [
      "Nombra todas sus variables en inglés, hasta las de la lista del súper.",
      "Tiene un mate con logo de terminal de Linux.",
      "Una vez debuggeó un error durante 6 horas: era un punto y coma.",
    ],
  },
  {
    id: 3,
    name: "Jairo Calla",
    role: "CSS & Frontend Developer",
    city: "San Salvador de Jujuy, Jujuy",
    age: 33,
    github: "https://github.com/JNCallaGiron",
    initials: "JC",
    fotoPerfil: "./img/perfil-2.png",
    fotoPerfil: "https://avatars.githubusercontent.com/u/12345678?v=4",
    accent: "#B24C1F",
    bio: "Cree que cualquier diseño, por imposible que parezca, se puede maquetar de forma limpia con Grid y Flexbox. Enemigo número uno del uso injustificado de '!important'.",
    skills: [
    { name: "CSS3 & SASS", level: 95 },
    { name: "Flexbox / CSS Grid", level: 90 },
    { name: "Animaciones y Transiciones", level: 85 },
    { name: "Tailwind CSS", level: 80 },
  ],
    movies: ["El gran hotel Budapest", "Coco", "Blade Runner 2049"],
    albums: ["La noche sin ti — Los Huayras", "Blonde — Frank Ocean", "Vida Cotidiana — Juanes"],
    funFacts: [
      "Tiene guardados 50 fragmentos de código (snippets) en CodePen 'por si acaso'.",
      "Todavía celebra internamente cada vez que logra centrar un div a la primera.",
      "Sufre físicamente cuando inspecciona una web y ve cinco <div> anidados de forma innecesaria.",
  ],
  },
  {
    id: 4,
    name: "Tomás Ledesma",
    role: "QA / Tester",
    city: "Mendoza, Mendoza",
    age: 27,
    github: "https://github.com/tomas-ledesma-qa",
    initials: "TL",
    fotoPerfil: "https://avatars.githubusercontent.com/u/12345678?v=4",
    accent: "#6B3FA0",
    bio: "Su deporte favorito es encontrarle la vuelta a un formulario hasta que explote. Si algo se puede romper, él ya lo rompió.",
    skills: [
      { name: "Testing manual", level: 90 },
      { name: "Selenium", level: 75 },
      { name: "NUnit / xUnit", level: 68 },
      { name: "Documentación de bugs", level: 88 },
    ],
    movies: ["Zodiac", "Prisioneros", "La red social"],
    albums: ["El Madrileño — C. Tangana", "AM — Arctic Monkeys", "Fuego Artificial — Bandalos Chinos"],
    funFacts: [
      "Encuentra el bug crítico cinco minutos antes del deploy, siempre.",
      "Tiene una lista de 'formas raras de romper un input' con más de 50 ítems.",
      "Su frase favorita es 'en mi máquina funciona' (para reírse de ella).",
    ],
  },
  {
    id: 5,
    name: "Sofía Benítez",
    role: "Fullstack Developer",
    city: "Santa Fe, Santa Fe",
    age: 23,
    github: "https://github.com/sofia-benitez-dev",
    initials: "SB",
    fotoPerfil: "https://avatars.githubusercontent.com/u/12345678?v=4",
    accent: "#1E7A8C",
    bio: "La que conecta todos los cables: si el front no le habla al back, ella arma el puente. Le gusta entender el sistema completo.",
    skills: [
      { name: "JavaScript", level: 85 },
      { name: "Node.js", level: 72 },
      { name: "Git avanzado", level: 80 },
      { name: "Metodologías ágiles", level: 76 },
    ],
    movies: ["Whiplash", "El juego de la imitación", "Steve Jobs"],
    albums: ["Norman F***ing Rockwell — Lana del Rey", "Vida — Nathy Peluso", "Random Access Memories — Daft Punk"],
    funFacts: [
      "Resuelve conflictos de merge con la misma calma que resuelve conflictos de equipo.",
      "Tiene un board de Trello para organizar sus otros boards de Trello.",
      "Aprendió a programar para automatizar una planilla de horarios del profesorado.",
    ],
  },
];
