/**
 * data.js
 * Fuente única de verdad para la información de las personas integrantes del equipo.
 * Todas las páginas (portada, perfiles) leen de este array. No hay datos
 * personales "hardcodeados" en el HTML: todo se renderiza desde acá vía JS.
 *
 * NOTA: la información es ficticia, generada para cumplir con la consigna del TP1.
 */

const TEAM = [
  {
    id: 1,
    name: "Omar Dario Virili",
    role: "Técnico superior en electrónica",
    city: "Villa Ocampo, Santa Fe",
    age: 42,
    github: "https://github.com/odv144",
    initials: "VR",
    fotoPerfil: "https://avatars.githubusercontent.com/u/12345678?v=4",
    accent: "#2B2F77",
    bio: "Apacionado por la electrónica y el desarrollo web, fasinado por la robótica y la Inteligencia Artificial.",
    skills: [
      { name: "HTML5 & CSS3", level: 92 },
      { name: "Java", level: 50 },
      { name: "React", level: 70 },
      { name: "Node.js", level: 65 },
      { name: "Python", level: 60 },
    ],
    movies: ["Matrix", "Ex Machina", "Una Mente Brillante"],
    albums: ["La Esquina del Infinito — La Renga", "Signos — Soda Stereo", "Say no more — Charly Gracía"],
    funFacts: [
      "De técnico en electrónica a programador: cambié los cables sueltos por bugs sueltos.",
      "Técnico en electrónica de día, programador de noche, fan del rock nacional las 24 horas.",
      "Soldé placas antes de soldar código, y a los dos les seguí sacando chispas",
    ],
  },
  {
    id: 2,
    name: "Bruno Aguirre",
    role: "Backend Developer",
    city: "Córdoba, Córdoba",
    age: 25,
    github: "https://github.com/bruno-aguirre-dev",
    initials: "BA",
    fotoPerfil: "https://avatars.githubusercontent.com/u/12345678?v=4",
    accent: "#1C6E5E",
    bio: "Diseña APIs pensando en quien las va a odiar a las 3am de un incidente: la persona del futuro que es él mismo.",
    skills: [
      { name: "Node.js", level: 88 },
      { name: "Bases de datos SQL", level: 82 },
      { name: "APIs REST", level: 85 },
      { name: "Docker", level: 60 },
    ],
    movies: ["Interestelar", "Sr. Robot (serie)", "WarGames"],
    albums: ["The Dark Side of the Moon — Pink Floyd", "In Rainbows — Radiohead", "Bahía — Louta"],
    funFacts: [
      "Nombra todas sus variables en inglés, hasta las de la lista del súper.",
      "Tiene un mate con logo de terminal de Linux.",
      "Una vez debuggeó un error durante 6 horas: era un punto y coma.",
    ],
  },
  {
    id: 3,
    name: "Milagros Cabrera",
    role: "UX/UI Designer",
    city: "Resistencia, Chaco",
    age: 21,
    github: "https://github.com/mili-cabrera",
    initials: "MC",
    fotoPerfil: "https://avatars.githubusercontent.com/u/12345678?v=4",
    accent: "#B24C1F",
    bio: "Cree que un buen diseño es el que nadie nota, porque todo funciona como uno espera. Fan de las paletas de 4 colores, ni uno más.",
    skills: [
      { name: "Figma", level: 90 },
      { name: "Diseño de sistemas", level: 78 },
      { name: "CSS avanzado", level: 74 },
      { name: "Prototipado", level: 85 },
    ],
    movies: ["El gran hotel Budapest", "Coco", "Blade Runner 2049"],
    albums: ["Un Verano Sin Ti — Bad Bunny", "Blonde — Frank Ocean", "Vida Cotidiana — Juanes"],
    funFacts: [
      "Guarda una carpeta con 400 paletas de color 'por si acaso'.",
      "Diseñó su primer wireframe en una servilleta.",
      "No perdona un espaciado inconsistente ni en un cartel de la calle.",
    ],
  },
  {
    id: 4,
    name: "Cynthia Sotelo",
    role: "QA MAnual - Automation",
    city: "Villa Carlos Paz",
    age: 46,
    github: "https://github.com/cynthia-sotelo",
    initials: "CS",
    fotoPerfil: "https://avatars.githubusercontent.com/u/12345678?v=4",
    accent: "#6B3FA0",
    bio: "Especialista en QA & Testing. Pongo a prueba el código para garantizar un software estable y confiable.",
    skills: [
      { name: "Cypress & Selenium", level: 85 },
      { name: ""APIs (Postman & Swagger)", level: 88 },
      { name: "Gestión de Bugs (Jira)", level: 90 },
      { name: "SQL & Bases de Datos", level: 75 },
    ],
    movies: ["El Padrino (trilogía)", "Pride and Prejudice", "Avengers - End Game"],
    albums: ["Abbey Road — The Beatles", "Revolver — The Beatles", "Greatest Hits I & II — Queen"],
    funFacts: [
      "Dirigente Scout los fines de semana, cazadora de bugs los demás días.",
      "Si un bug no aparece a la primera, aplico la máxima Scout: siempre lista para romper el código.",
      "Mi lema en testing es Help! I need somebody... pero solo para que aprueben el Pull Request.",
    ],
  },
  {
    id: 5,
    name: "Sofía Benítez",
    role: "Fullstack Developer",
    city: "Santa Fe, Santa Fe",
    age: 23,
    github: "https://github.com/sofia-benitez-dev",
    initials: "SB",
    fotoPerfil: "https://avatars.githubusercontent.com/u/12345678?v=4",
    accent: "#1E7A8C",
    bio: "La que conecta todos los cables: si el front no le habla al back, ella arma el puente. Le gusta entender el sistema completo.",
    skills: [
      { name: "JavaScript", level: 85 },
      { name: "Node.js", level: 72 },
      { name: "Git avanzado", level: 80 },
      { name: "Metodologías ágiles", level: 76 },
    ],
    movies: ["Whiplash", "El juego de la imitación", "Steve Jobs"],
    albums: ["Norman F***ing Rockwell — Lana del Rey", "Vida — Nathy Peluso", "Random Access Memories — Daft Punk"],
    funFacts: [
      "Resuelve conflictos de merge con la misma calma que resuelve conflictos de equipo.",
      "Tiene un board de Trello para organizar sus otros boards de Trello.",
      "Aprendió a programar para automatizar una planilla de horarios del profesorado.",
    ],
  },
];
